# Generated by Django 5.2.13 on 2026-05-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreayuda', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('objetivoFinaciero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('C', 'Objetivo conseguido'), ('X', 'Cancelado por la ONG')], default='A', max_length=1)),
                ('montonrecaudado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('cif', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='CIF')),
                ('nombrecompleto', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('documentacionLegal', models.FileField(blank=True, null=True, upload_to='documentos_ong/')),
                ('estado', models.CharField(choices=[('V', 'Sin verificar'), ('F', 'Fiable'), ('S', 'Sospechosa')], default='V', max_length=1)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('cartera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Imagen'), ('P', 'PDF')], default='P', max_length=1)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('montonjustificado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fechaGasto', models.DateField()),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='usuarios.ayuda')),
            ],
        ),
        migrations.AddField(
            model_name='ayuda',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_publicadas', to='usuarios.ong'),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodopago', models.CharField(choices=[('T', 'Tarjeta'), ('P', 'PayPal'), ('X', 'Transferencia')], default='T', max_length=1)),
                ('estado', models.CharField(max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayuda_donante', to='usuarios.ayuda')),
                ('dniusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donante', to='usuarios.usuario')),
            ],
        ),
    ]
